export const ActionTypes = {
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_FAIL: "REGISTER_FAIL",
    SET_REGISTER_VALIDATE_ERRORS: "SET_REGISTER_VALIDATE_ERRORS",
    CLEAR_REGISTER_VALIDATE_ERRORS: "CLEAR_REGISTER_VALIDATE_ERRORS",

    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAIL: "LOGIN_FAIL",
    SET_LOGIN_VALIDATE_ERRORS: "SET_LOGIN_VALIDATE_ERRORS",
    CLEAR_LOGIN_VALIDATE_ERRORS: "CLEAR_LOGIN_VALIDATE_ERRORS",

    AUTH_SUCCESS: "AUTH_SUCCESS",
    AUTH_FAIL: "AUTH_FAIL",

    LOGOUT: "LOGOUT",

    SET_MESSAGE: "SET_MESSAGE",
    CLEAR_MESSAGE: "CLEAR_MESSAGE",

    SET_LOADING: "SET_LOADING",
    CLEAR_LOADING: "CLEAR_LOADING",

    SET_CUSTOMERS: "SET_CUSTOMERS",
    ADD_CUSTOMER_STATUS: "ADD_CUSTOMER_STATUS",
    ADD_CUSTOMER: "ADD_CUSTOMER",
    ADD_CUSTOMER_FAIL: "ADD_CUSTOMER_FAIL",
    SET_CUSTOMER_VALIDATE_ERRORS: "SET_CUSTOMER_VALIDATE_ERRORS",
    CLEAR_CUSTOMER_VALIDATE_ERRORS: "CLEAR_CUSTOMER_VALIDATE_ERRORS",
    DELETE_CUSTOMER: "DELETE_CUSTOMER",
    SELECTED_CUSTOMER: "SELECTED_CUSTOMER",
    REMOVE_SELECTED_CUSTOMER: "REMOVE_SELECTED_CUSTOMER", 
    UPDATE_CUSTOMER: "UPDATE_CUSTOMER",
    UPDATE_CUSTOMER_STATUS: "UPDATE_CUSTOMER_STATUS",
    UPDATE_CUSTOMER_FAIL: "UPDATE_CUSTOMER_FAIL"
}