export const ActionTypes = {
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_FAIL: "REGISTER_FAIL",
    SET_REGISTER_VALIDATE_ERRORS: "SET_REGISTER_VALIDATE_ERRORS",
    CLEAR_REGISTER_VALIDATE_ERRORS: "CLEAR_REGISTER_VALIDATE_ERRORS",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAIL: "LOGIN_FAIL",
    LOGOUT: "LOGOUT",
    SET_MESSAGE: "SET_MESSAGE",
    CLEAR_MESSAGE: "CLEAR_MESSAGE "
}