export const AuthTypes = {
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_FAIL: "REGISTER_FAIL",
    SET_REGISTER_VALIDATE_ERRORS: "SET_REGISTER_VALIDATE_ERRORS",
    CLEAR_REGISTER_VALIDATE_ERRORS: "CLEAR_REGISTER_VALIDATE_ERRORS",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAIL: "LOGIN_FAIL",
    SET_LOGIN_VALIDATE_ERRORS: "SET_LOGIN_VALIDATE_ERRORS",
    CLEAR_LOGIN_VALIDATE_ERRORS: "CLEAR_LOGIN_VALIDATE_ERRORS",
    AUTH_SUCCESS: "AUTH_SUCCESS",
    AUTH_FAIL: "AUTH_FAIL",
    LOGOUT: "LOGOUT"    
}