export const CustomerTypes = {  
    SET_CUSTOMERS: "SET_CUSTOMERS",
    SET_ADD_CUSTOMER_STATUS: "SET_ADD_CUSTOMER_STATUS",
    ADD_CUSTOMER: "ADD_CUSTOMER",    
    SET_CUSTOMER_VALIDATE_ERRORS: "SET_CUSTOMER_VALIDATE_ERRORS",
    CLEAR_CUSTOMER_VALIDATE_ERRORS: "CLEAR_CUSTOMER_VALIDATE_ERRORS",
    DELETE_CUSTOMER: "DELETE_CUSTOMER",
    SET_SELECTED_CUSTOMER: "SET_SELECTED_CUSTOMER",
    REMOVE_SELECTED_CUSTOMER: "REMOVE_SELECTED_CUSTOMER", 
    UPDATE_CUSTOMER: "UPDATE_CUSTOMER",
    SET_UPDATE_CUSTOMER_STATUS: "SET_UPDATE_CUSTOMER_STATUS"    
}