export const LockTypes = {
    SET_LOCKS: "SET_LOCKS",

    ADD_LOCK: "ADD_LOCK",
    SET_ADD_LOCK_STATUS: "SET_ADD_LOCK_STATUS",

    SET_LOCK_VALID_ERRORS: "SET_LOCK_VALID_ERRORS",
    CLEAR_LOCK_VALID_ERRORS: "CLEAR_LOCK_VALID_ERRORS",

    DELETE_LOCK: "DELETE_LOCK",

    SET_SELECTED_LOCK: "SET_SELECTED_LOCK",
    REMOVE_SELECTED_LOCK: "REMOVE_SELECTED_LOCK",

    UPDATE_LOCK: "UPDATE_LOCK",
    SET_UPDATE_LOCK_STATUS: "SET_UPDATE_LOCK_STATUS"
}